"""
Test Suite: Auction Phase Simulation (Pre-7:00 AM vs Post-7:00 AM)
===================================================================

Enables testing the agent's behavior under both market phases at any time:
1. PRE_AUCTION (Pre-7:00 AM): Focuses on free agents sold by 'Mercado' (computer),
   applying competitive overbidding and auction hedging for critical gaps.
2. POST_AUCTION (Post-7:00 AM): Focuses on negotiating direct offers for players
   owned by rival managers, negotiating DOWN from asking prices.

Sends a full HTML newspaper email report for each phase tested so you can verify
the executive report in your inbox.

Usage:
    .venv/bin/python test/test_auction_phases.py --phase pre_auction
    .venv/bin/python test/test_auction_phases.py --phase post_auction
    .venv/bin/python test/test_auction_phases.py --all  (runs both phases and emails both)
"""

import sys
import os
import json
import pandas as pd
from datetime import datetime

# Add root directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.data_extraction.runner import orchestrate_pipeline
from src.agents.coach import Coach
from src.agents.sporting_director import SportingDirector
from src.utils.email_builder import render_action_email
from src.utils.email_templates import BASE_HTML_TEMPLATE
from src.utils.email_sender import send_report_email
from src.config import GeneralSettings
from jinja2 import Template


def send_phase_email(phase_name: str, decisions: dict, coach_report: dict, df_master: pd.DataFrame):
    print(f"\n📧 Building and sending HTML email report for phase: {phase_name.upper()}...")
    
    my_team = None
    try:
        if os.path.exists('./data/user_info.csv'):
            my_team = pd.read_csv('./data/user_info.csv')['team_name'].iloc[0]
    except Exception:
        pass
        
    execution_results = [
        f"🧪 Simulated {phase_name.upper()} Phase Execution Test",
        f"Total proposed bids: {len(decisions.get('operaciones_compra', []))}",
        f"Total proposed sales: {len(decisions.get('operaciones_venta', []))}",
    ]
    
    segments = render_action_email(
        coach_report,
        decisions,
        execution_results,
        df_master,
        my_team,
        projected_balance=decisions.get("analisis_financiero_previo", {}).get("saldo_proyectado_post_operaciones"),
    )
    
    _FOOTERS = {
        "es": "Generado por tu Biwenger Agent (Modo Test de Fases)",
        "en": "Generated by your Biwenger Agent (Phase Test Mode)",
    }
    footer_text = f"Biwenger Chronicle · {_FOOTERS.get(GeneralSettings.LANGUAGE, _FOOTERS['es'])}"
    
    template = Template(BASE_HTML_TEMPLATE)
    headline = f"[TEST SIMULADOR: {phase_name.upper()}] " + segments.get("headline", "Reporte de Biwenger Agent")
    
    html_content = template.render(
        lang=GeneralSettings.LANGUAGE,
        newspaper_name=f"BIWENGER CHRONICLE ({phase_name.upper()})",
        edition_line=f"{datetime.now().strftime('%A, %d %B %Y')} · Test Edition",
        headline=headline,
        lede=segments.get("lede", ""),
        stats_html=segments.get("stats_html", ""),
        sections=segments.get("sections", []),
        actions_html=segments.get("actions_html", ""),
        footer_line=footer_text,
    )
    
    friendly_summary = f"{headline}\n\n{segments.get('lede')}\n\n{segments.get('stats_html', '')}"
    subject = f"🗞️ Biwenger Chronicle - TEST SIMULADOR {phase_name.upper()} ({datetime.now().strftime('%d/%m %H:%M')})"
    
    success = send_report_email(friendly_summary, subject=subject, html_content=html_content)
    if success:
        print(f"   ✅ Email sent successfully to inbox for {phase_name.upper()}!")
    else:
        print(f"   ⚠️ Failed to send email for {phase_name.upper()}. Check SMTP config.")


def run_phase_test(phase_name: str, df_master: pd.DataFrame, coach_report: dict, send_email: bool = True):
    print("\n" + "=" * 70)
    print(f"🧪 TESTING PHASE: {phase_name.upper()}")
    print("=" * 70)
    
    sd = SportingDirector()
    decisions = sd.propose(coach_report, df_master, phase=phase_name)
    
    print("\n📊 --- DECISION SUMMARY ---")
    bids = decisions.get("operaciones_compra", [])
    sales = decisions.get("operaciones_venta", [])
    cancels = decisions.get("operaciones_cancelar_pujas", [])
    removals = decisions.get("operaciones_retirar_mercado", [])
    
    print(f"💰 Bids/Offers ({len(bids)}):")
    for b in bids:
        name = b.get("nombre", b.get("id_jugador_mercado"))
        amount = b.get("importe_oferta", 0)
        tipo = b.get("tipo_puja", "standard")
        print(f"   • {name}: €{amount:,} ({tipo})")
        
    print(f"🏷️ Sales ({len(sales)}):")
    for s in sales:
        name = s.get("nombre", s.get("id_jugador"))
        price = s.get("precio_minimo_esperado", 0)
        print(f"   • {name}: min €{price:,}")
        
    print(f"✖️ Bid Cancellations ({len(cancels)}):")
    for c in cancels:
        name = c.get("nombre", c.get("id_jugador"))
        print(f"   • {name}")

    if send_email:
        send_phase_email(phase_name, decisions, coach_report, df_master)

    return decisions


def main():
    print("=" * 70)
    print("⚡ BIWENGER AGENT - AUCTION PHASE SIMULATOR + EMAIL SENDER")
    print("=" * 70)
    
    # 1. Load or extract master dataframe
    df_master = orchestrate_pipeline(extract=False)
    if df_master is None or df_master.empty:
        print("📥 Extracting fresh live data...")
        df_master = orchestrate_pipeline(extract=True)
        
    # 2. Run Coach tactical analysis
    print("\n📋 Running Coach Analysis...")
    coach = Coach()
    coach_report = coach.analyze(df_master)
    
    # Parse CLI flags
    phase_to_run = "all"
    if "--phase" in sys.argv:
        idx = sys.argv.index("--phase")
        if idx + 1 < len(sys.argv):
            phase_to_run = sys.argv[idx + 1].strip().lower()
    elif "--all" in sys.argv or len(sys.argv) == 1:
        phase_to_run = "all"
        
    if phase_to_run in ("pre_auction", "all"):
        run_phase_test("pre_auction", df_master, coach_report, send_email=True)
        
    if phase_to_run in ("post_auction", "all"):
        run_phase_test("post_auction", df_master, coach_report, send_email=True)
        
    print("\n" + "=" * 70)
    print("✅ AUCTION PHASE SIMULATION & EMAIL SENDING COMPLETE!")
    print("=" * 70)


if __name__ == "__main__":
    main()
